name: 'Publish'
description: 'Publish the package to NPM'
runs:
  using: "composite"
  steps:
    - name: Set up authentication for package publishing
      env:
        NPM_PUBLISH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
      run: yarn config set npmAuthToken $NPM_PUBLISH_TOKEN
      shell: bash
    - name: Run yarn workspaces focus
      run: yarn workspaces focus --all --production
      shell: bash
    - name: Run yarn npm publish
      run: yarn npm publish
      shell: bash
