name: 'Publish'
description: 'Publish the package to NPM'
inputs:
  npm_publish_token:
    description: "NPM_PUBLISH_TOKEN"
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up authentication for package publishing
      env:
        NPM_PUBLISH_TOKEN: ${{ inputs.npm_publish_token }}
      run: yarn config set npmAuthToken $NPM_PUBLISH_TOKEN
      shell: bash
    - name: Run yarn workspaces focus
      run: yarn workspaces focus --all --production
      shell: bash
    - name: Run yarn npm publish
      run: yarn npm publish
      shell: bash
    - name: Create a Github release
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        PACKAGE_VERSION=$(jq -r .version < package.json)
        echo "PACKAGE_VERSION=${PACKAGE_VERSION}"
        gh release create "${PACKAGE_VERSION}" --generate-notes
