name: Trigger release

permissions:
  actions: none
  attestations: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: write
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Trigger release

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - name: Check if release is necessary
      uses: justincy/github-action-npm-release@f6afd60cbb595a76ecae037ad006671636d321f5 # v2.0.2
      id: release
    - name: Print release output
      if: steps.release.outputs.released == 'true'
      run: echo Release ID ${{ steps.release.outputs.release_id }}
    - uses: ./.github/actions/build/
      with:
        mode: "release"
      if: steps.release.outputs.released == 'true'
    - uses: ./.github/actions/publish/
      if: steps.release.outputs.released == 'true'
