name: Trigger release

permissions:
  actions: none
  attestations: none
  checks: none
  contents: write
  deployments: none
  discussions: none
  id-token: none
  issues: none
  packages: write
  pages: none
  pull-requests: none
  repository-projects: none
  security-events: none
  statuses: none

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Trigger release

    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      with:
        fetch-depth: 0
    - uses: ./.github/actions/check-release-status/
      id: release-status
    - uses: ./.github/actions/build/
      with:
        mode: "release"
      if: steps.release-status.outputs.already-released == 'false'
    - uses: ./.github/actions/publish/
      if: steps.release-status.outputs.already-released == 'false'
